language: python
sudo: required
dist: trusty
python:
- '2.7'
install: pip install tox-travis
before_script:
# Install RethinkDB
- wget http://deb.hozac.com/dhozac/ubuntu/trusty/rethinkdb_2.3.6+15+g8a9687+dirty~0_amd64.deb
- sudo apt install ./rethinkdb_2.3.6+15+g8a9687+dirty~0_amd64.deb
- sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/instance1.conf
- sudo invoke-rc.d rethinkdb start
# Install Firefox and geckodriver
- 'wget "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US"'
- tar -xjf firefox*.tar.bz2
- wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
- tar -xzf geckodriver-v0.20.0-linux64.tar.gz
# Install node
- curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
- sudo apt install -y nodejs xvfb
# Install JS dependencies
- npm install
env:
- HANDLE_COVERAGE=coveralls
script: xvfb-run -a tox
deploy:
  provider: pypi
  username: dhozac
  password:
    secure: sWLw8qK0IzIZ1nfeTZdBUEEY018+vAzD8qcOEpGenfuImu5lQCTCAyKzyw5Z/XEqMMIkiwLJylvE1Q6yxFgtc7ie65zs47Y3Qwep5O026eTp/QES6IxmOy4aXaEoBc7DfTMXjjTvp3U9oG/kHI/0a54Wf6MJTpeGLR010yt8GUBGEeyc2i5quvGC7xeAFeKwgxgJWQLeGiehmlkcFvGQ7XVFH5me5MbkCDrEkRy0PdHdChelVtMvGiB3wsdQhLBhOI4+JMCkAl7bxjMLBHlmTcWoqbS9NaOGWw2p0dNduiuARvlVz9Q8wSfslI9ZvyibfDRzAsD4nshvHw8w1YYL4yLwzVHSVNv9ZAnx3AwFeYF2KDPih1T0tteYM50pHhgjqtPEETZWPkCVZiEQ4dLRps7063T6XaNfaaMHbIyjFWbzxDpXRTJwcpcqS6I/fr/23uqp7WQg4qql2keZHE+a7rQStFUSF03WQHR1hYYUbDIfF5W95rAI678Ptvia+5HxxRyz7Pg1CCo2paaWxNz8qz8VVMb+yOY+OnZ/kfbjIHl0ZjHBF6j3F75octSJlLSaABC4Ho4IeE4e33AlY0hjjV9O5s3t+TXVH3V46WhfHo57arG4IabXpqLQVu2JUprp817wO1iAUy3aEr6tTRz63hz2FI9f1mpRBGO/Hw7Ksxw=
  on:
    tags: true
